# Generated by Django 3.1.3 on 2020-12-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
